project_name: "Rate Name Classifier"
port: 8000
version: "0.1.0"
models_dir: "../artifacts/models"
categories:
  - capacity
  - quality
  - view
  - bedding
  - balcony
  - bedrooms
  - club
  - floor
  - bathroom
  - class
